version: '3.8'
services:
  arucotag:
    image: ohin112/l4t-ubuntu20-yolo:cb
    container_name: cb_run
    tty: true  
    network_mode: host
    privileged: true
    cpuset: "0-2"
    runtime: nvidia

    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix

      - ../extraction-ws:/home/extraction-ws
      - ../realsense-ws:/home/realsense-ws
      - ../startup:/home/startup
      - ../system/.bashrc:/root/.bashrc:rw

    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev/bus/usb
    
    command: >
      /bin/bash -ic "cd /home/startup/; ./entrypoint.sh --blue"