version: '3'
services:
  ros1-main-program:
    build: 
      context: .  
      dockerfile: Dockerfile
    image: ohin112/l4t-ubuntu20-yolo:cb
    container_name: build
    tty: true
    privileged: true
    network_mode: host

    environment:
      - DISPLAY=${DISPLAY} 

    volumes:
      - ../extraction-ws:/home/extraction-ws
      - ../realsense-ws:/home/realsense-ws
      - ../startup:/home/startup

    command: >
      /bin/bash -ic "
      cd /home/extraction-ws 
      && catkin_make
      && chmod +x /home/extraction-ws/devel/*
      && cd /home/realsense-ws 
      && catkin_make
      "